name: Build LaTeX PDF on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout PR branch
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      # 2️⃣ Build PDF using LaTeX Action
      - name: Compile paper.tex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: paper.tex
          compiler: pdflatex

      # 3️⃣ Upload the compiled PDF as artifact
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: paper.pdf
