name: Build LaTeX PDF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build PDF
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Install LaTeX
      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra

      # 3️⃣ Build PDF
      - name: Compile paper.tex
        run: |
          pdflatex -interaction=nonstopmode paper.tex
          pdflatex -interaction=nonstopmode paper.tex  # twice for references

      # 4️⃣ Commit and push PDF if changed
      - name: Commit PDF
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add paper.pdf
          git diff --cached --quiet || git commit -m "Update compiled paper.pdf [skip ci]"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
